version: "3.2"
services:

  mongodb:
    image: mongo:3.6
    networks:
      - superdesk

  redis:
    image: redis:3
    networks:
      - superdesk

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    networks:
      - superdesk

  superdesk-server:
    image: sourcefabricoss/superdesk-server:demo
    depends_on:
      - redis
      - mongodb
      - elastic
    environment:
      - WEB_CONCURRENCY=2
      - SUPERDESK_CLIENT_URL=http://localhost:8080
      - MONGO_URI=mongodb://mongodb/test
      - PUBLICAPI_MONGO_URI=mongodb://mongodb/test_pa
      - LEGAL_ARCHIVE_URI=mongodb://mongodb/test_la
      - ARCHIVED_URI=mongodb://mongodb/test_ar
      - ELASTICSEARCH_URL=http://elastic:9200
      - ELASTICSEARCH_INDEX=superdesk
      - CELERY_BROKER_URL=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY
      - CONTENTAPI_URL=http://localhost:8080/capi
      - CONTENTAPI_MONGO_URI=mongodb://mongodb/test_ca
      - DEFAULT_TIMEZONE=Europe/Prague
    networks:
      - superdesk

  superdesk-client:
    image: sourcefabricoss/superdesk-client:demo
    environment:
      - SUPERDESK_URL=http://localhost:8080/api
      - SUPERDESK_WS_URL=ws://localhost:8080/ws
      - VIEW_DATE_FORMAT
      - VIEW_TIME_FORMAT
      - IFRAMELY_KEY
    depends_on:
      - superdesk-server
    ports:
      - "8080:80"
    networks:
      - superdesk

networks:
    superdesk:
        driver: bridge

volumes:
    superdesk:
