name: Publish Docker images

on:
  push:
    branches: []

jobs:
  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          context: server
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: superdesk/superdesk/superdesk-server
          tag_with_ref: true
          #username: ${{ secrets.DOCKER_USERNAME }}
          #password: ${{ secrets.DOCKER_TOKEN }}
          #repository: /superdesk-server
          #tag_with_ref: true
