name: Publish Docker images

on:
  push:
    branches: []

jobs:
  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Build and push image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          tags: sourcefabricoss/superdesk-test:latest
          context: server
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outpus.digest }}